server:
  servlet:
      context-path: /bgi
  port: 8081


spring:
  application:
    name: bgi
  config:
    import:
      - optional:file:./application-prod.yml
  profiles:
    active: prod

#  mvc:
#    # 推荐开启这个，让 /** 映射优先级低于静态资源
#    static-path-pattern: /static/**   # 可选，如果你想把静态资源路径改成 /static/ 开头
#    # throw-exception-if-no-handler-found: true   # 可选，404 时抛异常方便调试
#  web:
#    resources:
#      static-locations:
#        - classpath:/static/
    # 默认已经包含 classpath:/static/，通常不需要额外配置
    # 如果你把 dist 放在其他位置，可以加
    # static-locations: classpath:/static/,classpath:/public/

api:
  authorization: token
  common:
    version: 3.0.0
    title: SecuityAPI
    description: SecuityAPI
    termsOfService:
    license: 未经许可不得转载
    licenseUrl: xxx.license.com
    externalDocDesc:
    externalDocUrl:
    contact:
      name: kirito-asuna
      url:
      email:

springdoc:
  api-docs:
    path: /v3/api-docs
  # 请注意使用group名时如果配置了GroupedOpenApi引用自动配置时组名不能重复
  open:
    default-group-configs:
      enable: true
      api: true
      jwt: true
      other: true
  group-configs:
      - group: "api"
        paths-to-match: "/api/**"
      - group: "jwt"
        paths-to-match: "/jwt/**"
      - group: "other"
        paths-to-exclude:
          - "/swagger-resources/**"
          - "/v2/api-docs"
          - "/v3/api-docs"
          - "/api/**"
          - "/jwt/**"
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
    tags-sorter: alpha
#Authorization 在knife4j中失效==>替代方案 使用knife4j中全局参数设置Authorization
knife4j:
  cors: true
  enable: true
  setting:
    enable-dynamic-parameter: true
  #swagger
  basic:
    enable: false
    username: root
    password: root
